export { RedditAdsApiError } from "./internal/reddit-ads-api-error.js";
export {
  REDDIT_ADS_READ_VERIFICATION_MATRIX,
  runRedditAdsReadCanary,
  type RedditAdsReadCanaryOperation,
  type RedditAdsReadCanaryResult,
} from "./internal/read-canary.js";
export {
  createRedditAdsClient,
  DEFAULT_REDDIT_ADS_API_BASE_URL,
  type CreateRedditAdsClientOptions,
  type GetReportInput,
  type ListAdGroupsInput,
  type ListAdsInput,
  type ListBusinessAdAccountsInput,
  type ListCampaignsInput,
  type ListCommunitiesInput,
  type ListFundingInstrumentsInput,
  type ListMyBusinessesInput,
  type RedditAdsClient,
  type RedditPaginationInput,
} from "./internal/reddit-ads-client.js";
export type {
  RedditAd,
  RedditAdAccount,
  RedditAdAccountApproval,
  RedditAdAccountSuspensionReason,
  RedditAdEffectiveStatus,
  RedditAdGroup,
  RedditAdGroupSchedule,
  RedditAdGroupTargeting,
  RedditAdsApiErrorPayload,
  RedditAdsOAuthAuthorizationCodeParams,
  RedditAdsOAuthAuthorizationCodeTokenRequest,
  RedditAdsOAuthClientCredentials,
  RedditAdsOAuthDuration,
  RedditAdsOAuthRefreshTokenRequest,
  RedditAdsOAuthScope,
  RedditAdsOAuthScopeList,
  RedditAdsOAuthTokenResponse,
  RedditAdsPagination,
  RedditAttributionType,
  RedditAttributionWindow,
  RedditBusiness,
  RedditBusinessIndustry,
  RedditCampaign,
  RedditCampaignObjective,
  RedditCommunity,
  RedditConfiguredStatus,
  RedditExtensibleEnum,
  RedditFundingInstrument,
  RedditFundingInstrumentAuthorizeStatus,
  RedditFundingInstrumentCurrency,
  RedditFundingInstrumentInvoiceGroupStatus,
  RedditFundingInstrumentMode,
  RedditFundingInstrumentUnservableReason,
  RedditInterest,
  RedditMe,
  RedditPost,
  RedditPostContent,
  RedditPostSource,
  RedditPostType,
  RedditPixelPartnerPreference,
  RedditReportBreakdown,
  RedditReportField,
  RedditReportMetric,
  RedditReportMetricObject,
  RedditReportMetricScalar,
} from "./internal/types.js";
