export { TikTokAdsApiError } from "./internal/tiktok-ads-api-error.js";
export { TikTokAdsAmbiguousWriteError } from "./internal/tiktok-ads-ambiguous-write-error.js";
export {
  createTikTokAdsClient,
  DEFAULT_TIKTOK_API_VERSION,
  type CreateTikTokAdInput,
  type CreateTikTokCampaignInput,
  type CreateTikTokCustomAudienceInput,
  type UploadTikTokCustomAudienceFileInput,
  type CreateTikTokIdentityInput,
  type CreateTikTokLookalikeAudienceInput,
  type CreateTikTokPixelInput,
  type CreateTikTokAdsClientOptions,
  type GetTikTokBasicReportInput,
  type ListAuthorizedAdvertisersInput,
  type ListTikTokCampaignsInput,
  type ListTikTokInterestCategoriesInput,
  type ListTikTokCreativePortfoliosInput,
  type ListTikTokIdentitiesInput,
  type ListTikTokPixelsInput,
  type TikTokAdsClient,
  type TrackTikTokWebEventsInput,
  type UpdateTikTokCampaignStatusInput,
} from "./internal/tiktok-ads-client.js";
export type {
  TikTokAccessTokenRequest,
  TikTokAccessTokenResponse,
  TikTokAccessTokenResult,
  TikTokAdCreationResult,
  TikTokAdFormat,
  TikTokAdvertiserInfo,
  TikTokApiErrorBody,
  TikTokApiResponse,
  TikTokAuthorizedAdvertiser,
  TikTokBasicReportDataLevel,
  TikTokBasicReportDimension,
  TikTokBasicReportMetric,
  TikTokBasicReportResult,
  TikTokCampaignBudgetMode,
  TikTokCampaign,
  TikTokCampaignCreationResult,
  TikTokCampaignListResult,
  TikTokCampaignObjectiveType,
  TikTokCampaignOperationStatus,
  TikTokCampaignStatus,
  TikTokCampaignStatusUpdateResult,
  TikTokCreativePortfolio,
  TikTokCreativePortfolioFilterType,
  TikTokCreativePortfolioListResult,
  TikTokCreativePortfolioType,
  TikTokCreateOperationStatus,
  TikTokCustomAudienceCalculateType,
  TikTokCustomAudienceCreationResult,
  TikTokCustomAudienceFileUploadResult,
  TikTokIdentityCreationResult,
  TikTokIdentity,
  TikTokIdentityListResult,
  TikTokIdentityType,
  TikTokInterestCategory,
  TikTokInterestCategoryLanguage,
  TikTokInterestCategoryVersion,
  TikTokLookalikeAudienceSize,
  TikTokLookalikeLocationId,
  TikTokLookalikeMobileOs,
  TikTokLookalikePlacement,
  TikTokPageInfo,
  TikTokPixel,
  TikTokPixelListResult,
  TikTokPlacement,
  TikTokPostbackWindowMode,
  TikTokReportFilter,
  TikTokReportFilterType,
  TikTokReportOrderType,
  TikTokReportRow,
  TikTokSparkPullCallToAction,
  TikTokSpecialIndustry,
  TikTokTargetingLanguage,
  TikTokWebEvent,
  TikTokWebEventContent,
  TikTokWebEventContentType,
  TikTokWebEventCustomerType,
  TikTokWebEventPage,
  TikTokWebEventProperties,
  TikTokWebEventUser,
} from "./internal/types.js";
