export { LinkedInAdsApiError } from "./internal/linkedin-ads-api-error.js";
export { LinkedInAllocationGuardrailError } from "./internal/linkedin-allocation-guardrail-error.js";
export {
  buildLinkedInBriefDeploymentPlan,
  parseLinkedInCampaignBrief,
  type LinkedInBriefConcept,
  type LinkedInBriefDeploymentPlan,
  type LinkedInCampaignBrief,
} from "./internal/brief-deployment.js";
export {
  buildBoostPostPlan,
  createLinkedInAdsClient,
  DEFAULT_LINKEDIN_MARKETING_API_VERSION,
  type CreateLinkedInAdsClientOptions,
  type GetAnalyticsInput,
  type GetAnalyticsStatisticsInput,
  type LinkedInAdsClient,
  type ListCampaignsInput,
  type ListCampaignGroupsInput,
} from "./internal/linkedin-ads-client.js";
export {
  LINKEDIN_ADS_READ_VERIFICATION_MATRIX,
  runLinkedInAdsReadCanary,
  type LinkedInAdsReadCanaryInput,
  type LinkedInAdsReadCanaryOperation,
  type LinkedInAdsReadCanaryResult,
} from "./internal/read-canary.js";
export {
  DEFAULT_LINKEDIN_OPTIMIZATION_GUARDRAILS,
  applyLinkedInOptimizationActions,
  buildLinkedInOptimizationActions,
  detectLinkedInCreativeFatigue,
  recommendLinkedInCreativeAllocation,
  type LinkedInAllocationRecommendation,
  type LinkedInCreativeAllocation,
  type LinkedInFatigueAnalysis,
  type LinkedInOptimizationGuardrails,
  type LinkedInOptimizationAction,
} from "./internal/optimization.js";
export type {
  BoostLinkedInPostInput,
  BoostLinkedInPostPlan,
  CreateLinkedInCampaignInput,
  CreateLinkedInCampaignGroupInput,
  CreateLinkedInCreativeInput,
  CreateLinkedInLeadFormInput,
  GetLinkedInAudienceCountsInput,
  GetLinkedInCampaignConversionInput,
  LinkedInCampaignStatus,
  LinkedInAdAccountRole,
  LinkedInAdAccount,
  LinkedInAdAccountServingStatus,
  LinkedInAdAccountStatus,
  LinkedInAdAccountType,
  LinkedInAdAccountUser,
  LinkedInAnalyticsElement,
  LinkedInAnalyticsPivot,
  LinkedInAnalyticsStatisticsPivot,
  LinkedInAudienceCount,
  LinkedInAudienceCountTargetingCriteria,
  LinkedInApiErrorBody,
  LinkedInCampaign,
  LinkedInCampaignConversionAssociation,
  LinkedInCampaignGroupReadStatus,
  LinkedInCampaignGroupServingStatus,
  LinkedInCampaignPacingStrategy,
  LinkedInCampaignReadStatus,
  LinkedInCampaignServingStatus,
  LinkedInCampaignGroup,
  LinkedInCreative,
  LinkedInCreativeIntendedStatus,
  LinkedInCreativeReviewStatus,
  LinkedInCreativeServingHoldReason,
  LinkedInConversion,
  LinkedInConversionAttributionType,
  LinkedInConversionType,
  LinkedInImageUploadInput,
  ListLinkedInCreativesInput,
  ListLinkedInTargetingEntitiesInput,
  LinkedInDate,
  LinkedInElementsResponse,
  LinkedInLeadForm,
  LinkedInLeadFormResponse,
  LinkedInMoney,
  LinkedInOrganizationPost,
  LinkedInPaging,
  LinkedInTargetingCriteria,
  LinkedInTargetingEntity,
  LinkedInTargetingFacet,
  LinkedInTargetingLocale,
  LinkedInTimeGranularity,
  ListLeadFormResponsesInput,
  SearchLinkedInTargetingEntitiesInput,
  SearchLinkedInAdAccountsInput,
  UpdateLinkedInCampaignInput,
} from "./internal/types.js";
