export { LinkedInAdsApiError } from "./linkedin-ads-api-error.js";
export {
  buildBoostPostPlan,
  createLinkedInAdsClient,
  type CreateLinkedInAdsClientOptions,
  type GetAnalyticsInput,
  type LinkedInAdsClient,
  type LinkedInRequestOptions,
  type ListCampaignsInput,
} from "./linkedin-ads-client.js";
export type {
  BoostLinkedInPostInput,
  BoostLinkedInPostPlan,
  BoostLinkedInPostResult,
  CreateLinkedInCampaignInput,
  CreateLinkedInCreativeInput,
  CreateLinkedInLeadFormInput,
  LinkedInCampaignStatus,
  LinkedInAnalyticsElement,
  LinkedInAnalyticsPivot,
  LinkedInApiErrorBody,
  LinkedInCampaign,
  LinkedInCreative,
  LinkedInDate,
  LinkedInElementsResponse,
  LinkedInLeadForm,
  LinkedInLeadFormResponse,
  LinkedInMoney,
  LinkedInPaging,
  LinkedInTargetingCriteria,
  LinkedInTimeGranularity,
  ListLeadFormResponsesInput,
  UpdateLinkedInCampaignInput,
} from "./types.js";
