export { MetaAdsApiError } from "./meta-ads-api-error.js";
export {
  buildBoostPostPlan,
  createMetaAdsClient,
  type CreateMetaAdsClientOptions,
  type FindCampaignByNameInput,
  type GetInsightsInput,
  type GraphRequestOptions,
  type MetaAdsClient,
  type MetaAdsRequestOptions,
  type SearchAdLibraryInput,
} from "./meta-ads-client.js";
export type {
  ActionValue,
  AdLibraryResult,
  AdvertiserSummary,
  AudienceSchemaField,
  BoostPostInput,
  BoostPostPlan,
  BoostPostResult,
  CampaignSummary,
  ConversionActionSource,
  ConversionEvent,
  ConversionUserData,
  CreateAdCreativeInput,
  CreateAdInput,
  CreateAdSetInput,
  CreateCampaignInput,
  CreateCustomAudienceInput,
  CreateLookalikeAudienceInput,
  CustomAudienceInfo,
  CustomAudienceSubtype,
  DebugTokenData,
  DebugTokenResult,
  GraphApiError,
  GraphApiResponse,
  LeadForm,
  LeadRecord,
  LongLivedUserTokenResult,
  ManagedPageInfo,
  MetaAdsInsight,
  MetaAdsInsightLevel,
  MetaBillingEvent,
  MetaCampaignObjective,
  MetaCampaignStatus,
  MetaMutationIdResult,
  MetaOptimizationGoal,
  MetaTargetingSpec,
  ReachEstimateInput,
  ReachEstimateResult,
  SendConversionEventsInput,
  SendConversionEventsResult,
  SyncAudienceUsersInput,
  SyncAudienceUsersResult,
} from "./types.js";
