export { MetaAdsApiError } from "./internal/meta-ads-api-error.js";
export {
  MetaAdsContractDriftError,
  type MetaAdsContractDriftEvidence,
} from "./internal/meta-ads-contract-drift-error.js";
export {
  MetaAdsAmbiguousWriteError,
  type MetaAdsAmbiguousWriteEvidence,
} from "./internal/meta-ads-ambiguous-write-error.js";
export {
  buildBoostPostPlan,
  createMetaAdsClient,
  extractAdPreviewUrl,
  type ApplyAdLabelsInput,
  type CreateAsyncInsightsJobInput,
  type CreateAdLabelInput,
  type CreateAutomatedRuleInput,
  type CreateMetaAdsClientOptions,
  type DeleteAutomatedRuleInput,
  type FindCampaignByNameInput,
  type GenerateAdCreativePreviewsInput,
  type GetAdPreviewsInput,
  type GetAsyncInsightsJobInput,
  type GetAsyncInsightsJobResultsInput,
  type GetInsightsInput,
  type GetLeadsInput,
  type ListAdAccountActivitiesInput,
  type ListAdTargetingSentenceLinesInput,
  type ListAdLabelsInput,
  type ListAutomatedRulesInput,
  type ListCustomAudienceAdAccountsInput,
  type ListLeadFormsInput,
  type MetaAdsClient,
  type MetaAdsRequestOptions,
  type SearchAdLibraryInput,
  type ShareCustomAudienceInput,
  type SyncAdLabelsInput,
  type UpdateAutomatedRuleInput,
  type UnshareCustomAudienceInput,
} from "./internal/meta-ads-client.js";
export {
  DEFAULT_META_GRAPH_API_VERSION,
  type MetaGraphApiVersionPolicy,
  META_GRAPH_API_VERSION_POLICY,
} from "./internal/provider-version.js";
export {
  META_ADS_READ_VERIFICATION_MATRIX,
  type MetaAdsReadCanaryOperation,
  type MetaAdsReadCanaryResult,
  runMetaAdsReadCanary,
} from "./internal/read-canary.js";
export type {
  ActionValue,
  AdLibraryResult,
  AudienceDataSource,
  AudienceDataSourceType,
  AdvertiserSummary,
  AudienceSchemaField,
  AudienceUploadSession,
  AudienceUserValue,
  BoostPostInput,
  BoostPostPlan,
  BoostPostResult,
  CampaignSummary,
  ConversionActionSource,
  ConversionEvent,
  ConversionHashedUserDataValue,
  ConversionUserData,
  CreateAdCreativeInput,
  CreateAdInput,
  CreateAdSetInput,
  CreateCampaignInput,
  CreateCustomAudienceInput,
  CreateLookalikeAudienceInput,
  CustomAudienceCustomerFileSource,
  CustomAudienceAdAccount,
  CustomAudienceInfo,
  CustomAudienceSharingData,
  CustomAudienceSharingPermission,
  CustomAudienceSubtype,
  DebugTokenData,
  DebugTokenResult,
  GraphApiError,
  GraphApiResponse,
  LeadFieldData,
  LeadForm,
  LeadRecord,
  LongLivedUserTokenResult,
  ManagedPageInfo,
  MetaAdAccount,
  MetaAdAccountActivity,
  MetaAdAccountStatus,
  MetaAdCreativeAssetFeedSpec,
  MetaAdCreativeAssetFeedFormat,
  MetaAdCreativeAssetLabel,
  MetaAdCreativeAuthorizationCategory,
  MetaAdCreativeImageAsset,
  MetaAdCreativeLinkUrlAsset,
  MetaAdCreativeObjectStorySpec,
  MetaAdCreativeTextAsset,
  MetaAdCreativeVideoAsset,
  MetaAdLabel,
  MetaAdLabelApplyResult,
  MetaAdLabelSyncResult,
  MetaLeadgenWebhookChange,
  MetaLeadgenWebhookEntry,
  MetaLeadgenWebhookPayload,
  MetaLeadgenWebhookValue,
  KnownMetaAdPreviewFormat,
  MetaAdPreview,
  MetaAdPreviewFormat,
  MetaAdsActionAttributionWindow,
  MetaAdsInsightBreakdownPreset,
  MetaAdsInsight,
  MetaAdsInsightLevel,
  MetaAsyncInsightsJob,
  MetaAsyncInsightsJobCreateResult,
  MetaAsyncInsightsJobStatus,
  MetaAutomatedRule,
  MetaAutomatedRuleStatus,
  MetaBillingEvent,
  MetaCampaignObjective,
  MetaCampaignStatus,
  MetaMediaUploadBytes,
  MetaMutationIdResult,
  MetaMutationSuccessResult,
  MetaOptimizationGoal,
  MetaTargetingSentenceLine,
  MetaTargetingSpec,
  ReachEstimateInput,
  ReachEstimateResult,
  SendConversionEventsInput,
  SendConversionEventsResult,
  ShareCustomAudienceResult,
  SyncAudienceUsersInput,
  SyncAudienceUsersResult,
  UpdateAdInput,
  UpdateAdSetInput,
  UpdateCampaignInput,
  UploadAdImageInput,
  UploadAdImageResult,
  UploadedAdImage,
  UploadAdVideoInput,
  UploadAdVideoResult,
} from "./internal/types.js";
