import { defineConfig } from "tsdown";

export default defineConfig({
  clean: true,
  dts: { generator: "tsgo" },
  entry: [
    "src/index.ts",
    "src/mutation-canary.ts",
    "src/core/index.ts",
    "src/rest/index.ts",
    "src/oauth.ts",
    "src/reports/index.ts",
    "src/research/index.ts",
    "src/resolvers/index.ts",
    "src/compliance/index.ts",
    "src/partial-failure.ts",
    "src/cloudflare/index.ts",
    "src/workflows/negative-keywords.ts",
    "src/workflows/pause-ad-groups.ts",
    "src/workflows/add-keywords.ts",
    "src/workflows/remove-keywords.ts",
    "src/workflows/add-ad-groups.ts",
    "src/workflows/asset-set-linkage.ts",
    "src/workflows/audience-segments.ts",
    "src/workflows/bidding-adjustments.ts",
    "src/workflows/bidding-strategies.ts",
    "src/workflows/shared-set-negative-keywords.ts",
    "src/workflows/update-ad-final-urls.ts",
    "src/workflows/update-campaign-budget.ts",
    "src/workflows/update-campaign-bidding.ts",
    "src/workflows/conversion-goals.ts",
    "src/workflows/recommendations.ts",
    "src/workflows/update-responsive-search-ads.ts",
    "src/workflows/campaign-assets.ts",
    "src/workflows/campaign-criteria.ts",
    "src/workflows/performance-max-asset-groups.ts",
    "src/workflows/performance-max-listing-groups.ts",
    "src/workflows/update-campaign-locations.ts",
    "src/workflows/update-ad-group-demographics.ts",
    "src/workflows/set-campaign-frequency-cap.ts",
    "src/workflows/set-campaign-max-cpc.ts",
    "src/workflows/create-campaign-experiment.ts",
    "src/workflows/deploy-campaign.ts",
    "src/deploy/parse-brief.ts",
    "src/deploy/types.ts",
  ],
  fixedExtension: false,
  format: ["esm"],
  platform: "neutral",
});
